### PR TITLE
Add Git LFS Support

### LINKED ISSUE #115: 希望支持lfs同步
### 当前

不支持lfs同步, 源头可以使用git lfs pull下载lfs内容; 在目的端git lfs pull报错,找不到objects

### 期望

希望可以提供lfs同步开关, 支持lfs内容同步,同步命令参考

```
# 下载lfs内容
git lfs fetch --all {来源URL}
# 推送lfs内容
git lfs push --all {目标URL}
```

### PR DESCRIPTION
**Pull request by kareemZarka**
This pull request introduces support for Git LFS (Large File Storage) 

- Added the necessary steps to install Git LFS in the docker/entrypoint.
- Updated the `_clone` and `_update` methods to fetch Git LFS objects during cloning and updating operations.
- Modified the `push` method to push Git LFS objects along with regular repository content

Closes: https://github.com/Yikun/hub-mirror-action/issues/115

### CODE REVIEW

**Review by Yikun — CHANGES_REQUESTED** [review]
Thanks for contributions! Great work!

I think it's OK to me to support it, but I'd more like to introduce with a option parameter like `lfs`.

By default, lfs is set to `false`. Only enable the addition lfs fetch/push, when user set `lfs` to true.

You can also test it by using something like

```
- name: Git LFS support
  uses: kareemZarka/hub-mirror-action@support-lfs
  with:
    src: github/your_github_repo
    dst: gitee/your_gitee_repo
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    lfs: true
```

Pls also fix flake8 error and do a E2E test by above setting in your personal repo then paste the link.

Then I'd like to merge this.

**Review by Yikun — APPROVED** [review]
LGTM! I added doc and example for `lfs` support.

If no more question, I will merge it today.

**Comment by kareemZarka** [comment]
@Yikun perfect! thank you!!

**Comment by kareemZarka** [comment]
@Yikun perfect! thank you!!

**Comment by Yikun** [comment]
@kareemZarka Thanks for contributions, merged. 

You can use below steps to have a test, if no more issue, I'd like to release a new version: v1.4 .

```
- name: Mirror with lfs (git lfs fetch/push --all)
  uses: Yikun/hub-mirror-action@master
  with:
    // ... ..
    lfs: true
```

**Comment by Yikun** [comment]
@kareemZarka Any feedback about lfs feature?

**Pull request merged**
